/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homework4sql;

import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SOL
 */
public class frmCustomers extends frmSuperForm{

    /**
     * Creates new form frmCustomers
     */
    boolean checkNew;
    String editContact_id;

    public frmCustomers(Connection sqlpass, String id, String firstname, String lastname,
        String address, String city, String country, String contactType, String contact_id, boolean bNew, DefaultTableModel tbl) {
        super(sqlpass);
        
        boolean check = cnf.isDbConnected(con);
        //System.out.println(check);

        if (!check) {
            JOptionPane.showMessageDialog(null, "SQL Connection Failed or Interrupted.");
            return;
        }
        
        setDefaultTable(tbl);
        initComponents();

        checkNew = bNew;

        if (!bNew) {
            txtCustomer_id.setText(id);
        }

        txtCustomer_first_name.setText(firstname);
        txtCustomer_last_name.setText(lastname);
        txtCustomer_address.setText(address);
        txtCustomer_city.setText(city);
        txtCustomer_country.setText(country);
        cmbBoxContact.setSelectedItem(contactType);
        editContact_id = contact_id;
    }

    @Override
    protected void loadData() {
        getCnf().getDefaultContact(getCon(), getDefaultTable()); // Load contact data into tblCostomers
    }

    @Override
    protected void refreshTable()
    {
        DefaultTableModel model = (DefaultTableModel) getDefaultTable();
        model.setRowCount(0);
        getCnf().getDefaultCustomer(getCon(), getDefaultTable());
    }
    //see frmMain for details
//    public boolean isDbConnected(Connection con) {
//        try {
//            return con != null && !con.isClosed();
//        } catch (SQLException ignored) {
//            System.out.println("sql failed to connect");
//        }
//        return false;
//    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirstName = new javax.swing.JLabel();
        txtCustomer_first_name = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtCustomer_last_name = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCustomer_city = new javax.swing.JTextField();
        lblAdress = new javax.swing.JLabel();
        txtCustomer_address = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtCustomer_country = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        txtCustomer_id = new javax.swing.JTextField();
        lblCustomerID = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        cmbBoxContact = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Database - Customer Table");
        setResizable(false);

        lblFirstName.setText("First Name:");

        txtCustomer_first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomer_first_nameActionPerformed(evt);
            }
        });

        lblLastName.setText("Last Name:");

        txtCustomer_last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomer_last_nameActionPerformed(evt);
            }
        });

        lblCity.setText("City:");

        txtCustomer_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomer_cityActionPerformed(evt);
            }
        });

        lblAdress.setText("Address:");

        txtCustomer_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomer_addressActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtCustomer_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomer_countryActionPerformed(evt);
            }
        });

        lblCountry.setText("Country:");

        txtCustomer_id.setEditable(false);
        txtCustomer_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomer_idActionPerformed(evt);
            }
        });

        lblCustomerID.setText("ID:");

        lblContact.setText("Contact Type:");

        cmbBoxContact.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phone", "Cell", "Work", "Email", "Fax" }));
        cmbBoxContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName)
                            .addComponent(lblAdress)
                            .addComponent(lblCity)
                            .addComponent(lblCountry)
                            .addComponent(lblCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContact))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCustomer_city, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomer_first_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomer_last_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomer_address, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomer_country, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomer_id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBoxContact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAdress, lblCity, lblCountry, lblFirstName, lblLastName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomer_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCustomer_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtCustomer_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(txtCustomer_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCustomer_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(txtCustomer_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContact)
                    .addComponent(cmbBoxContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnExit))
                .addGap(8, 8, 8))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCustomer_address, txtCustomer_city, txtCustomer_country, txtCustomer_first_name, txtCustomer_last_name});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAdress, lblCity, lblCountry, lblFirstName, lblLastName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExit, btnSave});

        getAccessibleContext().setAccessibleName("Database - Customer List");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomer_first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomer_first_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomer_first_nameActionPerformed

    private void txtCustomer_last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomer_last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomer_last_nameActionPerformed

    private void txtCustomer_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomer_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomer_cityActionPerformed

    private void txtCustomer_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomer_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomer_addressActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if(getCnf().saveCustomer(con, checkNew, txtCustomer_id, txtCustomer_first_name, txtCustomer_last_name, txtCustomer_city, txtCustomer_address, txtCustomer_country, 
                cmbBoxContact, editContact_id ))
        {
            refreshTable();
            this.dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        //exit the tab without saving data
        refreshTable();
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtCustomer_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomer_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomer_countryActionPerformed

    private void txtCustomer_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomer_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomer_idActionPerformed

    private void cmbBoxContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxContactActionPerformed

    /**
     * @param args the command line arguments *
     */
    //code from internet modified to check connection just in case it doesnt pass
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbBoxContact;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JTextField txtCustomer_address;
    private javax.swing.JTextField txtCustomer_city;
    private javax.swing.JTextField txtCustomer_country;
    private javax.swing.JTextField txtCustomer_first_name;
    private javax.swing.JTextField txtCustomer_id;
    private javax.swing.JTextField txtCustomer_last_name;
    // End of variables declaration//GEN-END:variables

}
