/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homework4sql;

import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SOL
 */
public class frmContact extends frmSuperForm{

    /**
     * Creates new form frmCustomers
     */     

    boolean checkNew;
    boolean addExist;
    String exist_id = "";

    public frmContact(Connection sqlpass, String id, String contactType, boolean bNew, boolean addExistContact, String e_id, DefaultTableModel tbl) {
        super(sqlpass);
        initComponents();
        setDefaultTable(tbl);

        boolean check = cnf.isDbConnected(con);
        System.out.println(check);
        
        if (!check) {
            JOptionPane.showMessageDialog(null, "SQL Connection Failed or Interrupted.");
            return;
        }

        checkNew = bNew;
        addExist = addExistContact;
        exist_id = e_id;
        
        if (!checkNew) {
            txt_ContactID.setText(id);
        }

        txt_ContactID.setText(id);

        for (int i = 0; i < cmBox_ContactType.getItemCount(); i++) {
            Object item = cmBox_ContactType.getItemAt(i);
            if (contactType != null && contactType.equals(item.toString())) {
                cmBox_ContactType.setSelectedIndex(i);
                break;
            }
        }
    }
    @Override
    protected void loadData() {
        getCnf().getDefaultContact(getCon(), getDefaultTable()); // Load contact data into tblCostomers
    }
    @Override
    protected void refreshTable() {
        getDefaultTable().setRowCount(0);
        getCnf().getDefaultContact(getCon(), getDefaultTable());
    }
    
    

    //see frmMain for details
//    public boolean isDbConnected(Connection con) {
//        try {
//            return con != null && !con.isClosed();
//        } catch (SQLException ignored) {
//            System.out.println("sql failed to connect");
//        }
//        return false;
//    }


   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCustomer_id = new javax.swing.JTextField();
        lblCustomerID = new javax.swing.JLabel();
        txtCustomer_id1 = new javax.swing.JTextField();
        lblCustomerID1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txt_ContactID = new javax.swing.JTextField();
        lblContactType = new javax.swing.JLabel();
        lblContactID = new javax.swing.JLabel();
        cmBox_ContactType = new javax.swing.JComboBox<>();

        txtCustomer_id.setEditable(false);
        txtCustomer_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomer_idActionPerformed(evt);
            }
        });

        lblCustomerID.setText("ID:");

        txtCustomer_id1.setEditable(false);
        txtCustomer_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomer_id1ActionPerformed(evt);
            }
        });

        lblCustomerID1.setText("ID:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Database - Customer Table");
        setResizable(false);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txt_ContactID.setEditable(false);
        txt_ContactID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ContactIDActionPerformed(evt);
            }
        });

        lblContactType.setText("Contact Type:");

        lblContactID.setText("Contact ID:");

        cmBox_ContactType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phone", "Cell", "Work", "Email", "Fax" }));
        cmBox_ContactType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmBox_ContactTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContactID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContactType, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_ContactID, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBox_ContactType, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactID)
                    .addComponent(txt_ContactID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactType)
                    .addComponent(cmBox_ContactType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnExit))
                .addGap(47, 47, 47))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExit, btnSave});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(getCnf().saveContact(con, checkNew, addExist, exist_id, cmBox_ContactType, txt_ContactID))
        {
            if(addExist)
            {
                getDefaultTable().setRowCount(0);
                getCnf().getDefaultCustomer(getCon(), getDefaultTable());
                this.dispose();
            }
            else{
                refreshTable();
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        refreshTable();
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txt_ContactIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ContactIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ContactIDActionPerformed

    private void txtCustomer_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomer_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomer_idActionPerformed

    private void txtCustomer_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomer_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomer_id1ActionPerformed

    private void cmBox_ContactTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmBox_ContactTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmBox_ContactTypeActionPerformed

    /**
     * @param args the command line arguments *
     */
    //code from internet modified to check connection just in case it doesnt pass
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmBox_ContactType;
    private javax.swing.JLabel lblContactID;
    private javax.swing.JLabel lblContactType;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerID1;
    private javax.swing.JTextField txtCustomer_id;
    private javax.swing.JTextField txtCustomer_id1;
    private javax.swing.JTextField txt_ContactID;
    // End of variables declaration//GEN-END:variables
}
