/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package homework4sql;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SOL
 */
public class frmPublisherDatabase extends frmSuperList {

    /**
     * Creates new form frmGameDatabase
     */
    public frmPublisherDatabase(Connection sqlpass){
        super(sqlpass);
        initComponents();

        DefaultTableModel tableModel = (DefaultTableModel) tblPublisherDatabase.getModel();
        
        try {
            Statement stmt = con.createStatement();
            //change name of schema for your datbase,
            ResultSet rs = stmt.executeQuery("SELECT * FROM project.game");

            while (rs.next()) {
                //fetch data from sql datatable
                String id = rs.getString("game_id");
                String game_title = rs.getString("game_title");
                String publisher_id = rs.getString("publisher_id");
                String release_date = rs.getString("release_date");
                //add to table
                tableModel.addRow(new Object[]{id, game_title, publisher_id, release_date});

            }
            //close statement on completion
            stmt.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: cannot retrieve the data table");
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPublisherDatabase = new javax.swing.JTable();
        btnAddPublisher = new javax.swing.JButton();
        btnUpdatePublisher = new javax.swing.JButton();
        btnDeletePublisher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPublisherDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "publisher_id", "name"
            }
        ));
        jScrollPane1.setViewportView(tblPublisherDatabase);

        btnAddPublisher.setText("Add Publisher");
        btnAddPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPublisherActionPerformed(evt);
            }
        });

        btnUpdatePublisher.setText("Update Publisher");
        btnUpdatePublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePublisherActionPerformed(evt);
            }
        });

        btnDeletePublisher.setText("Delete Publisher");
        btnDeletePublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePublisherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdatePublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeletePublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnAddPublisher)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdatePublisher)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletePublisher)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPublisherActionPerformed
        // TODO add your handling code here:
        getCng().newPublisher(getCon(), getTable()); //.newGame(getCon(), getTable());
      //getCnf().newContact(getCon(), getTable(), false, null);
    }//GEN-LAST:event_btnAddPublisherActionPerformed

    private void btnUpdatePublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePublisherActionPerformed
        // TODO add your handling code here:
        getCng().editPublisher(getCon(), getTable());
    }//GEN-LAST:event_btnUpdatePublisherActionPerformed

    private void btnDeletePublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePublisherActionPerformed
        // TODO add your handling code here:
        if(getCng().deletePublisher(getCon(), getTable()))
        {
            refreshTable();
        }
    }//GEN-LAST:event_btnDeletePublisherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPublisherDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPublisherDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPublisherDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPublisherDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPublisher;
    private javax.swing.JButton btnDeletePublisher;
    private javax.swing.JButton btnUpdatePublisher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPublisherDatabase;
    // End of variables declaration//GEN-END:variables
}
