-- MySQL Script generated by MySQL Workbench
-- Tue Jul  9 17:30:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `project` ;

-- -----------------------------------------------------
-- Table `mydb`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`publisher` (
  `publisher_id` INT NOT NULL,
  `publisher_name` VARCHAR(45) NULL,
  PRIMARY KEY (`publisher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`game` (
  `game_id` INT NOT NULL,
  `game_title` VARCHAR(45) NULL,
  `publisher_id` INT NOT NULL,
  `release_date` DATE NULL,
  PRIMARY KEY (`publisher_id`, `game_id`),
  CONSTRAINT `fk_game_publisher1`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `mydb`.`publisher` (`publisher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`sales` (
  `game_id` INT NOT NULL,
  `publisher_id` INT NOT NULL,
  `sales` INT NULL,
  PRIMARY KEY (`game_id`, `publisher_id`),
  INDEX `fk_sales_publisher1_idx` (`publisher_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_publisher1`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `mydb`.`publisher` (`publisher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game_population`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`game_population` (
  `game_id` INT NOT NULL,
  `player_count` INT NULL,
  `region` VARCHAR(45) NULL,
  PRIMARY KEY (`game_id`),
  CONSTRAINT `fk_game_population_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`game_genre` (
  `game_id` INT NOT NULL,
  `genre` VARCHAR(45) NULL,
  PRIMARY KEY (`game_id`),
  CONSTRAINT `fk_game_genre_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`game_platform` (
  `game_id` INT NOT NULL,
  `platform` VARCHAR(45) NULL,
  PRIMARY KEY (`game_id`),
  CONSTRAINT `fk_game_platform_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`price` (
  `game_id` INT NOT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`game_id`),
  CONSTRAINT `fk_price_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
